title: Major Project
description: >- # this means to ignore newlines until "baseurl:"
  Short posts about simple tools I'm working on.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ritinlal.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ritinlal 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
